
**Q1: Questions on Basic NumPy Array
(a) Reverse the NumPy array: arr = (b) Flatten the NumPy arr: array1 = NumPy in-built methods
(c) Compare the following numpy arrays:
np.array([1, 2, 3, 6, 4, 5])
np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array([1,2,3,4,5,1,2,1,1,1])
np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = ii. y = (e) For the array gfg = i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise
np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix
(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?**


In [7]:
import numpy as np


#1a
arr=np.array([1,2,3,6,4,5])

reveresed=arr[::-1]
reveresed

#1b
array_1=np.array([[1,2,3],[2,4,5],[1,2,3]])


array_flatten=array_1.flatten()

array_flatten


#1c
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])


print(arr1==arr2)



#1d
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])



def most_unique_and_indices(arr):

 values ,count=np.unique(arr,return_counts=True)
 most_frequent=values[np.argmax(count)]

 indices=np.where(arr==most_frequent)

 return most_frequent , indices


print(most_unique_and_indices(x))
print(most_unique_and_indices(y))


#1e

gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')

print("The sum of the array is : ", gfg.sum())

coloumn_sum=gfg.sum(axis=0)
print("The sum of the array is : ", coloumn_sum)

row_sum=gfg.sum(axis=1)
print("The sum of the array is : ", row_sum)


#1f

n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
trace = np.trace(n_array)
eigenvalues, eigenvectors=np.linalg.eig(n_array)
inverse=np.linalg.inv(n_array)
determinant=np.linalg.det(n_array)

print("The value of trace of matrix: ", trace)
print("The value of eigenvalues of matrix: ", eigenvalues)
print("The value of eigenvectors of matrix: ", eigenvectors)
print("The value of inverse of matrix: ", inverse)
print("The value of determinant of matrix: ", determinant)

#1g

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.matmul(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())

p2 = [[1, 2],
      [2, 3],
      [4, 5]]

q2 = [[4, 5, 1],
      [6, 7, 2]]


p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

product2 = np.matmul(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())



xx= np.array([[2, 3, 4],
              [3, 2, 9]])

yy= np.array([[1, 5, 0],
              [5, 10, 3]])

inner_product = np.inner(x, y)

outer_product = np.outer(x, y)

from itertools import product
cartesian_product = np.array(list(product(x.flatten(), y.flatten())))

print("Inner Product:\n", inner_product)
print("Outer Product:\n", outer_product)
print("Cartesian Product:\n", cartesian_product)









[[ True  True]
 [ True  True]]
(np.int64(1), (array([0, 5, 7, 8, 9]),))
(np.int64(1), (array([0, 1, 2]),))
The sum of the array is :  45
The sum of the array is :  [[20  9 16]]
The sum of the array is :  [[14]
 [16]
 [15]]
The value of trace of matrix:  176
The value of eigenvalues of matrix:  [98.16835147 28.097044   49.73460452]
The value of eigenvectors of matrix:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
The value of inverse of matrix:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
The value of determinant of matrix:  137180.0000000001
Inner Product:
 47
Outer Product:
 [[ 1  1  1  2  3  4  2  4  3  3]
 [ 2  2  2  4  6  8  4  8  6  6]
 [ 3  3  3  6  9 12  6 12  9  9]
 [ 4  4  4  8 12 16  8 16 12 12]
 [ 5  5  5 10 15 20 10 20 15 15]
 [ 1  1  1  2  3  4  2  4  3  3]
 [ 2  2  2  4  6  8  4  8  6  6]
 [ 1  1  1  2  3  4  2  4  3  3]
 [ 1  

**Q2: Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row
(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values**

In [6]:
import numpy as np

# 2(a)
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i.
abs_array = np.abs(array)

# ii.
percentiles_flattened = np.percentile(array, [25, 50, 75])
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

# iii.
mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_flattened = np.std(array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceil_values = np.ceil(a)
trunc_values = np.trunc(a)
round_values = np.round(a)

print("Part (a):")
print("Absolute value:\n", abs_array)
print("Percentiles (flattened):", percentiles_flattened)
print("Percentiles (columns):\n", percentiles_columns)
print("Percentiles (rows):\n", percentiles_rows)
print("Mean (flattened):", mean_flattened)
print("Median (flattened):", median_flattened)
print("Std Dev (flattened):", std_flattened)
print("Mean (columns):", mean_columns)
print("Median (columns):", median_columns)
print("Std Dev (columns):", std_columns)
print("Mean (rows):", mean_rows)
print("Median (rows):", median_rows)
print("Std Dev (rows):", std_rows)

print("\nPart (b):")
print("Floor values:", floor_values)
print("Ceiling values:", ceil_values)
print("Truncated values:", trunc_values)
print("Rounded values:", round_values)



Part (a):
Absolute value:
 [[1 2 3]
 [4 5 6]]
Percentiles (flattened): [-3.5 -0.5  2.5]
Percentiles (columns):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (rows):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (flattened): -0.5
Median (flattened): -0.5
Std Dev (flattened): 3.8622100754188224
Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Std Dev (columns): [2.5 3.5 4.5]
Mean (rows): [ 0.66666667 -1.66666667]
Median (rows): [ 1. -4.]
Std Dev (rows): [2.05480467 4.78423336]

Part (b):
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


**Q3: Based on Searching and Sorting
(a) For the array: array = i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements
(b) For the array: array = i. Integer elements only
ii. Float elements only
np.array([10, 52, 62, 16, 16, 54, 453]), find
np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find**

In [8]:
#3
import numpy as np

# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
four_smallest = np.sort(array)[:4]
five_largest = np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", four_smallest)
print("5 largest elements:", five_largest)

# (b)
array_float = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

int_elements = array_float[array_float % 1 == 0]
float_elements = array_float[array_float % 1 != 0]

print("\nInteger elements only:", int_elements)
print("Float elements only:", float_elements)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


 **Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)
(b) Load the saved file into jupyter notebook?**

In [10]:

from google.colab import files

uploaded = files.upload()  # Upload your image file here
# After upload, the filename(s) will be keys in `uploaded`


import cv2
import numpy as np
import os

def img_to_array(path):
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if img is None:
        print("Error: Image not found or unable to read.")
        return

    if len(img.shape) == 2:
        print("Image is grayscale.")
        txt_filename = os.path.splitext(path)[0] + "_grayscale.txt"
        np.savetxt(txt_filename, img, fmt='%d')
        print(f"Grayscale image saved as text file: {txt_filename}")

    elif len(img.shape) == 3 and img.shape[2] == 3:
        print("Image is color (BGR).")
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        txt_filename = os.path.splitext(path)[0] + "_rgb.txt"
        reshaped = img_rgb.reshape(-1, 3)
        np.savetxt(txt_filename, reshaped, fmt='%d', header='R G B', comments='')
        print(f"RGB image saved as text file: {txt_filename}")
    else:
        print("Unsupported image format or number of channels.")



Saving Aryan.jpg to Aryan (1).jpg


In [11]:
img_to_array("Aryan.jpg")


Image is color (BGR).
RGB image saved as text file: Aryan_rgb.txt


In [14]:
from google.colab import files

files.download("Aryan_rgb.txt")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [19]:
def load_image_array(txt_path, is_rgb=True, original_shape=None):
    import numpy as np
    data = np.loadtxt(txt_path, skiprows=1)
    if is_rgb:
        if original_shape:
            data = data.reshape(original_shape)
        return data.astype(np.uint8)
    else:
        if original_shape:
            data = data.reshape(original_shape)
        return data.astype(np.uint8)

import cv2

img = cv2.imread("Aryan.jpg")
if img is None:
    print("Error: Image not found or unable to read.")
else:
    print("Original shape:", img.shape)
    original_shape = img.shape

    rgb_array = load_image_array("Aryan_rgb.txt", is_rgb=True, original_shape=original_shape)
    print("Loaded array shape:", rgb_array.shape)








Original shape: (720, 1280, 3)
Loaded array shape: (720, 1280, 3)
